In [1]:
import numpy as np

In [3]:
#assign input values
input_value=np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [4]:
#assign the output values
output=np.array([0,1,1,0])
output=output.reshape(4,1)
output.shape

(4, 1)

In [5]:
#assign weights
weights=np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [6]:
#add bias
bias=0.3

In [10]:
#activation function
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [11]:
#derivative of sigmoid function
def der(x):
    return sigmoid_func(x)*(1-sigmoid_func(x))

In [16]:
#updating weights
for epochs in range(10000):
    input_arr=input_value
    weighted_sum=np.dot(input_arr,weights)+bias
    first_output=sigmoid_func(weighted_sum)
    error=first_output-output
    total_error=np.square(np.subtract(first_output,output)).mean()
    #print(total_error)
    first_der=error
    second_der=der(first_output)
    derivative=first_der+second_der
    t_input=input_value.T
    final_derivative=np.dot(t_input,derivative)
    #update weights
    weights=weights-0.05*final_derivative
    #update bias
    for i in derivative:
        bias=bias-0.05*i
print(weights)
print(bias)

[[ -1.23053867]
 [252.07148732]]
[-250.77722698]


In [22]:
#prediction
pred=np.array([0,1])
result=np.dot(pred,weights)+bias
res=sigmoid_func(result)
print(res)

[0.78486742]
